// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadContextUsage } from "./ThreadContextUsage";
import type { TokenUsageBreakdown } from "./TokenUsageBreakdown";

export type ThreadTokenUsage = { total: TokenUsageBreakdown, last: TokenUsageBreakdown, modelContextWindow: number | null,
/**
 * Active context usage; absent for snapshots recorded without it.
 */
contextUsage: ThreadContextUsage | null, };
