// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool-result cleanup progress for a loaded thread's current model route.
 */
export type ThreadToolCleanupStatus = {
/**
 * Whether background tool marking runs on the current model route.
 */
enabled: boolean,
/**
 * Whether a background marking request is in flight.
 */
marking: boolean,
/**
 * Estimated context tokens released by applying every current validated mark.
 */
pendingSavingsTokens: number,
/**
 * Release required before automatic cleanup applies the marks.
 */
requiredSavingsTokens: number, };
