// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnTokenUsage } from "./TurnTokenUsage";

export type ThreadTokenUsageReadResponse = {
/**
 * The last token usage recorded in each turn of the thread's own history, in turn order.
 */
data: Array<TurnTokenUsage>, };
