// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadChatTreeNode } from "./ThreadChatTreeNode";

export type ThreadChatTree = { currentNodeId: string | null, nodes: Array<ThreadChatTreeNode>, };
