// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadContextUsageBreakdown } from "./ThreadContextUsageBreakdown";

/**
 * Active model context usage; `tokens` is the value that drives automatic compaction.
 */
export type ThreadContextUsage = { tokens: number,
/**
 * Active context tokens at which automatic compaction triggers, when it can trigger.
 */
autoCompactTokenLimit: number | null,
/**
 * Estimated composition of `tokens`; categories sum exactly to `tokens`.
 */
breakdown: ThreadContextUsageBreakdown, };
