// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadToolCleanupStatus } from "./ThreadToolCleanupStatus";

export type ThreadToolCleanupApplyResponse = {
/**
 * Estimated context tokens released; zero when no mark could shorten the history.
 */
releasedTokens: number, status: ThreadToolCleanupStatus, };
