// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadContextUsageBreakdown = { baseInstructions: number, developerInstructions: number, agentsMd: number, skills: number, tools: number, environment: number, userMessages: number, agentMessages: number, toolCalls: number, reasoning: number, compaction: number, other: number, };
